### PR TITLE
Fixed import to support multi project Pods

### PR DESCRIPTION
**Pull request by mohpor**
As of CocoaPods 1.7.0, you can decide if your Pods setup is MultiProject, it will improve the performance of Large projects' build, but it break some imports decorations.

This PR dresses the import problem of the CocoaSecurity Module.

Signed-off-by: Mohammad Porooshani <porooshani@gmail.com>

### CODE REVIEW

**Comment by mohpor** [comment]
@nielsmouthaan Do you think it is possible to have this asap.
I have a rather large project awaiting this one Pod to be able to updated.

Weird as it is, I cannot use my own fork as pod's source because it cannot find any pod spec!
🤷🏻‍♂️

**Comment by nielsmouthaan** [comment]
@mohpor I (blindly) merged your PR without bumping up the version as I have limited time. Could you check if this works?

**Comment by mohpor** [comment]
will do

**Comment by mohpor** [comment]
But from past experience, it won't, so, if this is possible, please make a release tag.

**Comment by mohpor** [comment]
@nielsmouthaan 
It didn't work BTW, I'm still waiting on you to bump the version and do a trunk push to pod

**Pull request merged**
